site_name: DXB211 Notes
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep purple
  features:
    - navigation.path
    - toc.integrate   
    - navigation.top
    - search.highlight
    - navigation.tracking
    - navigation.indexes 
    - toc.follow
     - navigation.sections
  plugins:
  - search
repo_url: http://peachnono/DXB211_notes
markdown_extensions:
  - attr_list